### ISSUE TITLE
New Repo- DSA README file update

### ISSUE THREAD

**Issue by akrish4** [MakeContributions/DSA#1]
Here is the repo DSA 

Need to update the readme file @ming-tsai   @paulsonjpaul

**Comment by ming-tsai** [comment]
Okis

**Comment by ming-tsai** [comment]
Hi @akrish4,
Could you describe how to use and the contribution guideline?

**Comment by akrish4** [comment]
i would suggest like to open a issue all the time when a new topic or program is added to a particular DSA topic so that we can avoid duplication of the codes from multiple users and maintainers can assign it to the ones who raise the issue will be given top priority to work on it.
right ? what do you say  @ming-tsai   @paulsonjpaul

**Comment by ming-tsai** [comment]
I'm agreed

**Comment by paulsonjpaul** [comment]
Good idea 👍

**Comment by paulsonjpaul** [comment]
Add some description in the README (what this repo is about, etc.)

**Comment by akrish4** [comment]
yeah , we need to update readme file

**Comment by ming-tsai** [comment]
Hi @akrish4, please check the contribution guideline on readme

**Comment by paulsonjpaul** [comment]
Shall we close this issue and continue the discussion in #38?
