### ISSUE TITLE
Two Sum in JavaScript

### ISSUE THREAD

**Issue by Maniktherana** [MakeContributions/DSA#1008]
## Information about Algorithm

Given an array of integers ``nums`` and an integer ``target``, return indices of the two numbers such that they add up to ``target``.
You may assume that each input would have exactly one solution, and you may not use the same element twice.
You can return the answer in any order.
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

This is a competitive platform problem from [leetcode](https://leetcode.com/problems/two-sum/description/)

**Comment by Amarjeet2909** [comment]
I want to solve this issue and contribute in it

**Comment by Ayushitgithub** [comment]
i want to work on this plz assign to me
