### ISSUE TITLE
Linear Search in C++ In Vector & Array Both

### ISSUE THREAD

**Issue by Amarjeet2909** [MakeContributions/DSA#1030]
## Information about Algorithm

Linear Search can be done in Vector and array in C++ in sequential fashion .
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

(Type here)

**Comment by Amarjeet2909** [comment]
Dear Sir/Ma'am, I have created this Issue and I would like to solve this. So please give me the opportunity

**Comment by ashutosh-gupta2111** [comment]
Hello, Can you please assign this issue to me?

**Comment by Amarjeet2909** [comment]
#include <bits/stdc++.h>
#include <stdio.h>
using namespace std;

int main(){
    int n,key;
    cout<<"Enter the number of elements\n";
    cin>>n;

    //Declaring the Array
    int A[n];

    cout<<"Enter the Elements\n";
    for(int i=0;i<n;i++)
    {
        cin>>A[i];
    }
    cout<<"Enter the element to Search\n";
    cin>>key;

    //Linear Search
    for(int i=0;i<n;i++)
    {
        if(A[i]==key){
            cout<<"Element found at Location "<<i+1<<endl;
        }
    }

    //Linear Search In Vector
    int number;
    vector<int> V;
    cout<<"Enter the Number of Element to Insert in Vector\n";
    cin>>number;

    for(int i=0;i<number;i++){
        int element;
        cin>>element;
        V.push_back(element);
    }
    
    cout<<"Enter the element to Search\n";
    cin>>key;

    //Linear Search
    for(int i=0;i<n;i++)
    {
        if(V[i]==key){
            cout<<"Element found at Location "<<i+1<<" In Vector V"<<endl;
        }
    }

    return 0;
}
//This code is contributed by Amarjeet Singh

**Comment by ming-tsai** [comment]
Please add a pull request using git or read this [article](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md)

**Comment by yashh1234** [comment]
Please assign me this @ming-tsai

**Comment by ming-tsai** [comment]
> Please assign me this @ming-tsai

Hi @yashh1234,
This is duplicate issue.
