### ISSUE TITLE
typo in the yml job, supposed to be "greeting", not "greating"

### ISSUE THREAD

**Issue by gauthamkrishna9991** [MakeContributions/DSA#105]

**Comment by TawfikYasser** [comment]
Hi @gauthamkrishna9991 , You can work on it to fix this typo

Open a PR and start working on it.

**Comment by gauthamkrishna9991** [comment]
Issue is fixed and PR proposed [here](https://github.com/MakeContributions/DSA/pull/107#issue-589231443).
