### ISSUE TITLE
Bad memory usage in  DSA/algorithms/CPlusPlus/Graphs/dijkstra.cpp 

### ISSUE THREAD

**Issue by Denisthatorf** [MakeContributions/DSA#1058]
The Dijkstra algorithm uses vector<vector<pair<int,int>>> graph(V+1,vector<pair<int,int>>()) as a matrix. This is very, very bad for memory, because the vector in the vector in memory is not stored linearly, and can be scattered in memory very much. As an alternative, I propose to use a regular array (data = new T [rows * columns]) allocated on the heap and get its elements like this : *(_data + row * _rows + column).

**Comment by ming-tsai** [comment]
Hi @Denisthatorf,
Could you help me to this bug?

**Comment by Denisthatorf** [comment]
Yes, sure

**Comment by Denisthatorf** [comment]
https://github.com/MakeContributions/DSA/pull/1061 - my pull request for fixing a problem
