### ISSUE TITLE
Proposal for improved naming scheme

### ISSUE THREAD

**Issue by gauthamkrishna9991** [MakeContributions/DSA#108]
Since the programs presently aren't kept in it's own directory, it would make sense to have an organisation for programs, by keeping it in its own directory (**PLEASE GO THROUGH PROPOSED SOLUTIONS IN THE BOTTOM**), as that provides better isolation **than just filenames**.
**For example**: Consider the tree of directory [**`DSA/arrays/c-or-cpp` @ `cdaefaf`**](https://github.com/MakeContributions/DSA/tree/cdaef8f/arrays/c-or-cpp)
```bash
DSA/arrays/c-or-cpp
├── count-inversions.cpp
├── dutch-flag-algo.cpp
├── left-rotation.cpp
└── shift-negatives.cpp
```
**Is easy to understand but difficult to organise**, compared to a directory structure, that looks like this
```bash
DSA/arrays/c-or-cpp
├── count-inversions
│   └── main.cpp
├── dutch-flag-algo
│   └── main.cpp
├── left-rotation
│   └── main.cpp
└── shift-negatives
    └── main.cpp
```
For now, this organisation works, but for the future, potentially even the not-so-far future it wouldn't work out well, when it would contain >50 programs all in a single directory, which would also make it easier for programs to have it's own `Makefiles` or other program-specific settings as it gets bigger.

It could change the folder naming also, **but** it is, in my opinion, a better plan for the future so that for some problems, a program could be it's own isolated organised project.

# Pros and Cons
- **PRO:** Better organisation of problems & programs.
- **PRO:** Allows for proper program conventions, for source code files.
- **PRO:** Allows for organized test files to be added to it.
- **PRO:** **Easily allow inclusion of associative files for the project like `Makefiles` (for C/C++), `requirements.txt` (Python), `package.json` (NodeJS), `Cargo.toml` (Rust), `go.mod` (Go) and the like.**
- **CON:** Potentially more difficult repository to go through (though this can be worked out with more polished set of instructions for contribution).
- **CON:** Could become difficult for newcomers unless we categorize what contribution is considered simple and what's not.
# Proposed solutions:
1. #### Modification of all the programs to conform to `category/language/problem/(program/app/main).ext` instead of `category/language/problem.ext`
    ### Pros and cons
    - **PRO:** Could be beneficial in the long run
    - **CON:** More tedious. Someone has to work on this.
    - **CON:** Potentially error-prone
2. #### Extension of the file and naming specifications to also **accommodate for complex or more elaborate programs also**, which would let a specific class of programs (especially ones that comes with `Makefiles` and the like), be easier to add as a contribution.
    ### Pros and cons
    - **PRO:** Easier to implement.
    - **PRO:** Could allow for more classes of more complex programs being allowed for it, along with keeping support for simpler ones.
    - **CON:** Could make the repository files more fragmented.
    - **CON:** Could make it difficult for new-comers to understand how the new naming-scheme works unless it's explained well (I could put time into working the instructions for that also).

**Comment by ming-tsai** [comment]
Hi @gauthamkrishna9991,
Is something like this #9?

**Comment by gauthamkrishna9991** [comment]
No actually. More like for a problem, it's either a problem `problem.ext` or a folder `problem` with a `main.ext` file.

It's not a categorisation, but rather organizing larger **single** programs in its own folder. It's a level of isolation instead of categorisation. 

It's important for when you want to accommodate larger projects. 

Given time I'll be able to provide a few examples.

**Comment by ming-tsai** [comment]
Ok

**Comment by ming-tsai** [comment]
I prefer a project or folder for each language, what do you think @Arsenic-ATG, @paulsonjpaul, @gauthamkrishna9991, @TawfikYasser, and @akrish4?

**Comment by TawfikYasser** [comment]
Yes @ming-tsai  I am agree with you

**Comment by gauthamkrishna9991** [comment]
I agree with you partly about this. This proposal would reduce the cohesiveness and the simplicity of a project and also would introduce fragmentations on the directories.

Though would severely limit the flexibility of contributions (as in rust, though it's possible to have a single file being passed as program, it always is written & distributed with  `Cargo.toml` file in a directory, or in  Java where each class is file (also would come with a `pom.xml` or a `build.gradle` file), which is also similar to C# (which contains the `.csproj` file) and C/C++ (which 
is sometimes also divided to different files, and also usually comes with `Makefiles`).

I don't think a directory would be much different in my opinion, from that, to this:
```bash
DSA
├── arrays
│   ├── c-or-cpp
│   │   ├── count-inversions.cpp
│   │   ├── dutch-flag-algo.cpp
│   │   ├── left-rotation.cpp
│   │   └── shift-negatives.cpp
│   ├── java
│   │   └── count-inversions.java
│   ├── js
│   │   ├── array-rotations # -> this is a directory which aligns to the naming convention.
│   │   │   ├── main.js       # -> main.js function for this
│   │   │   └── package.json # -> package.json which keeps dependencies, if needed.
│   │   └── count-inversions.js
│   ├── python
│   │   └── count-inversions.py
│   └── README.md
└── graphs
    ├── c-or-cpp
    │   ├── array-rotations # -> a C++ **project** for array rotation algorithm
    │   │   ├── main.cpp    # the main entry point
    │   │   └── Makefile    # the Makefile for building the program.
    │   ├── kruskal-algorithm.cpp
    │   └── README.md
    └── README.md
```

# A proposal for updated contribution guidelines

## 1. Folder or file structure & naming
The folder or file should have the following conditions:
- The file or folder name must be in **lowercase**.
- Each word should be seperated with a **dash (-)**
- When we have a new broad topic, we should create a new folder and index for it.
- A new file (or the main file) must be added to the **index(README.md)** using relative links
- It can only contain **dash(-)** as it cannot have other specific characters.

Structure
```bash
DSA
| problem
  | language
    | problem.ext
    | problem2
      | main.ext
      | file1.ext
      | buildfile / requirements / specs file
```
Example
```bash
DSA
| arrays
  | c-or-cpp
    | kruskals-algo.cpp
    | array-rotations
      | main.cpp
      | Makefile
      | array-rotations.sln
 | python
   | kruskals-algo.py
   | array-rotations
     | main.py
     | requirements.txt
```

**DO NOTE THAT THE CONVENTION NEEDS TO BE FOLLOWED IN EACH FOLDER UNLESS IT'S OVERRIDDEN BY THE LANGUAGE CONVENTIONS, IN WHICH CASE LAUNCH AN ISSUE.**

## 2. Naming Conventions

The programming should keep the naming convention rule of each programming language.

**Comment by Arsenic-ATG** [comment]
yes, it actually make sense especially when someone is trying to make his/her own full fledged data structure ( like a custom vector class in C++ ) then it would make more sense to put the actual class and it's implementation in separate files (possibly a static or dynamic library which can later be linked to the program for faster execution ) and will also make it possible to use it independently in other programs also. 

and because all the files would be with same name ( eg `main.cpp` ) then it would make it possible for us to provide newcomers with a template MAKEFILE for them to just copy paste in their folder in case they are not aware of how to make one on their own and are just submitting a single file program 

additionally having folder for each submission instead of a file will open up opportunity for contributor to create a `readme.md` for their program to put all the information about the algorithm and it's implantation in a more appealing way compared to putting them in form of comments on the top of program.

---- 

@ming-tsai I think this will only require contribution guidelines to be updated for someone who is willing make a comparatively larger contribution and we can keep the current form of the repository as it is, making it possible for developer of almost every skill level to contribute to this repo without much of a hassle.

**Comment by ming-tsai** [comment]
I'm agree

**Comment by gauthamkrishna9991** [comment]
A few examples which could need directories for a problem.

Though a few extra files in the directory would also be needed, like a standalone `README.md` file, and a `.gitignore` file.

- **Rust (`rust`):** Almost all single rust programs are always organised and distributed as part of a project.

  A program/project in `rust` has a directory tree of the following structure.

   ```bash
  problem/
    | Cargo.toml
    | src
      | main.rs
  ```
- **JavaScript (`js`):** A lot of projects that make use of `npm` also sometimes use `package.json` to resolve dependencies or to describe the main `.js` file.

There are more, but I am not remembering others, other than these, C/C++ `Makefiles`and Java `Maven`/`Gradle`, and Python `requirements.txt`.

**Comment by ming-tsai** [comment]
So, we are going to have for each problem has its solution or project file?

**Comment by gauthamkrishna9991** [comment]
Not really. For simple ones we still keep the file based problem specification / convention. It's upto the contributor whether their problem requires a single file or a project.

We can have specific specifications we can work on, also, if the contribution is a project. The specification should be broad enough that most everyone should be able to run it easily and should be strict enough to be sure that there aren't any low quality contributions also.

**Comment by gauthamkrishna9991** [comment]
I can elaborate on it.

**Comment by ming-tsai** [comment]
> I can elaborate on it.
Could you fork the repo and create some examples?

**Comment by gauthamkrishna9991** [comment]
Sure.

**Comment by ming-tsai** [comment]
@gauthamkrishna9991 could you help update the contributions guidelines?

**Comment by gauthamkrishna9991** [comment]
Sure.

**Comment by gauthamkrishna9991** [comment]
The name of the **project directory-based problem** follows what we did for the **single file-based problem** we did before, minus the file extension of course.

As I understand, I think the better naming for all these would be `category` or `topic` (a common category which a subset of these problems belong to) => `language` (the base programming language the problem is written in) => `contribution` or `problem` (which is the single unit of problem contribution) 

To iterate a possible directory tree structure:
```bash
category                 # problem category or topic
| - language             # language source code
    | - problem-1.ext    # simple problem contribution
    | - problem2         # a more elaborate problem contribution
        | - Makefile     # or any well-known configuration/specification/build-file
        | - README.md    # this describes the problem being added to the project
        | - src/         # source can be in the src/ directory, or in the root project directory
            | - main.ext # the main source file, it can be App.ext or main.ext or index.ext as long as 
                         # the path to the file is trivially known or specifically described in README
```
Though, I do think, adding a **link to the source code (if not trivially known) in project-specific `README.md` file is also a good thing to have** (not really needed when it is trivially known, like `./src/main.ext` for a few languages, and `./main.ext` for others.

Instead of `category/language/README.md`->`category/language/source.ext`, we might need to put `category/language/README.md`->`category/language/problem/README.md`->`category/language/problem/[path-to-source-file]` for list of links for this.

# Contribution Guidelines (updated)

## 1. Contribution Specifications

The problem being contributed must either be a simple **file** ([`kruskal-algorithm.cpp`] (https://github.com/MakeContributions/DSA/blob/main/graphs/c-or-cpp/kruskal-algorithm.cpp), [`linear-search.java`](https://github.com/MakeContributions/DSA/blob/main/searching/java/linear-search.java)) or a more complex **directory** ([`palindrome/`](https://github.com/MakeContributions/DSA/tree/main/strings/rust/palindrome)). This is a unit `problem`.

The directory tree has the following convention of `category/language/problem`, where `category` is the topic or category of the  problem being contributed (`strings`,`sorting`,`linked-lists` etc.), `language` represents the language code of the problem (`c-or-cpp` for C/C++, `python` for Python, `java` for Java etc. ), and `problem` is a conforming name to the problem

A unit `problem` must conform to the following specifications:
- The name should be in lowercase. (`palindrome/`, `binary-search.cpp`etc.).
- Each word must be seperated by a **dash** or a **hyphen** (`-`).

####  If you have a problem that belongs to a new *topic* or *category* than one which are present:
1. Create a new folder and an index for it inside (a readme, `README.md` file). (
2. To each new index file, write the readme with your `problem` in it ([Markdown Documentation](https://guides.github.com/features/mastering-markdown/)).
3. The folder name can also only contain **lowercase characters** and **dashes** or **hyphens** (`-`) (Eg. `strings` `sorting` etc.)

### Simple (File) Contributions

The file should conform to the `problem` specification, and the extension (Eg. `linear-search.java`, `kruskal-algorithm.cpp`, `count-inversions.js` etc.)

### Project/Folder-based Contributions

The project and folder-based contributions have a bit more stricter contribution contribution specifications.

The folder should conform to the `problem` specification, along with the following specifications:
```bash
problem-name\
| - .gitignore
| - README.md
| - Makefile       # or the specific specification/requirements/configuration file
| - src\
    | - main.ext
```

#### - `README.md` Specification / Template

```markdown
# <Title of the Problem>

< description of the problem >

## Prerequisites

- prerequisite library or package
- [prerequisite library](https://www.example.com/link-to-official-library)

## Instructions

- instructions to run the project
- < Simple and reproducible commands to execute the project >
    ```bash
     make # or 'cargo run', or 'dotnet run' or 'mvn exec:java' etc.
    ```
## Test Cases & Output < if exists>

< If you can provide test cases, describe it here, else remove this section >
```
#### - `.gitignore` File
```gitignore
# add all output files and build files to be excluded from git tracking
main     # executable file also must have the project name
target/  # the build file, for example for rust
```

#### - Build File / Specification File / Configuration File
It can be any of the following ones
- **C/C++**: `Makefile`
- **Python**: `requirements.txt`
- **JavaScript**: `package.json` and `package-lock.json`
- **Rust**: `Cargo.toml` and `Cargo.lock`
- **Go**: `go.mod`

### - Source Code File

The source code files, should either be in `src/` folder (for example `src/main.cpp` or `src/index.js`) or the root folder (`palindrome.go` or App.java`) where `ext` is the file extension for the specific programming language.

**We can discuss about modifications about the above.**

**Comment by ming-tsai** [comment]
@gauthamkrishna9991 could you creating the pull request, so it will be easier to review it

**Comment by gauthamkrishna9991** [comment]
Done.
