### ISSUE TITLE
 reverse a string using recursion in javascript

### ISSUE THREAD

**Issue by madhumitha-b** [MakeContributions/DSA#1172]
## Information about Algorithm

I would like to contribute an algorithm that would reverse a string using recursion in javascript
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

This is a competitive platform problem i.e. Hackerrank,Codechef,GeeksforGeeks,Leetcode,Codeforce

**Comment by Sagar180304** [comment]
#1173
