### ISSUE TITLE
We should encourage that submisssions have tests

### ISSUE THREAD

**Issue by cclauss** [MakeContributions/DSA#169]
Our GitHub Actions should run testing engines for the various programming languages and we should encourage all new submissions come with tests... #170 will add more tests to the list below.

% `pytest --doctest-modules .`
```
============================= test session starts ==============================
platform linux -- Python 3.9.4, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/runner/work/DSA/DSA
collected 11 items

arrays/python/count-inversions.py .                                      [  9%]
multiplication/python/karatsuba.py ....                                  [ 45%]
scheduling/python/interval-scheduling.py .                               [ 54%]
sorting/python/bubble-sort.py .                                          [ 63%]
sorting/python/insertion-sort.py .                                       [ 72%]
sorting/python/quick-sort.py .                                           [ 81%]
sorting/python/selection-sort.py .                                       [ 90%]
strings/python/palindrome.py .                                           [100%]

============================== 11 passed in 0.11s ==============================
```
Other opportunities:
* [ ] linked-lists/Python/singly.py
* [ ] searching/python/binary-search.py
* [ ] searching/python/jump-search.py
* [ ] searching/python/linear-search.py
* [x] strings/python/palindrome.py #172

**Comment by ming-tsai** [comment]
Nice work, so would you like to help me with this issue?

**Comment by cclauss** [comment]
@ming-tsai I would be interested to see _others_ jump in and create tests for the remaining files listed in the checklist above.

**Comment by ming-tsai** [comment]
Yes @cclauss

**Comment by atin** [comment]
Is it okay if I add more tests or should I wait for others to do it? @ming-tsai @cclauss

**Comment by cclauss** [comment]
I see no advantage in waiting... go for it!

**Comment by ming-tsai** [comment]
Yes you could make contributions as you want

**Comment by atin** [comment]
After merging these PRs all python files will have doctests in them so I think this issue can be closed after merging. @cclauss can you verify?

**Comment by cclauss** [comment]
Other programming languages can not be tested?

**Comment by atin** [comment]
Oh, yeah. I thought this issue is just for python doctests. Then maybe can you add more subtasks? I can do that but I'm not able to edit the issue.

**Comment by atin** [comment]
I'll try to add more tests in `go` and `cpp`
