### ISSUE TITLE
Open Graph is not drawing

### ISSUE THREAD

**Issue by ming-tsai** [MakeContributions/DSA#171]
Hi @TawfikYasser,
Could you help me to check this?
![image](https://user-images.githubusercontent.com/37890026/114558591-d6285080-9c38-11eb-9aee-03cbc4b7efba.png)

**Comment by TawfikYasser** [comment]
Okay @ming-tsai  I'll see the problem and try to fix it.

**Comment by ming-tsai** [comment]
> Okay @ming-tsai I'll see the problem and try to fix it.

Any update?

**Comment by TawfikYasser** [comment]
## I think it is now working well, It was a problem with the API itself.

![og](https://user-images.githubusercontent.com/54971231/115323394-59412d80-a188-11eb-8b10-0026f4578f43.png)

**Comment by ming-tsai** [comment]
Thanks
