### ISSUE TITLE
Action Python Error

### ISSUE THREAD

**Issue by TawfikYasser** [MakeContributions/DSA#175]
Hi @cclauss 

I think there is a problem here 
![Screenshot 2021-04-13 185507](https://user-images.githubusercontent.com/54971231/114591104-d270ea00-9c89-11eb-9ab3-e5faa6e237a2.png)

Thanks

**Comment by cclauss** [comment]
Clicking the Details hotlink is a good idea...
```
Run codespell --ignore-words-list="ans,nnumber" --quiet-level=2
./stacks/JAVA/The_Stock_Span_Problem.java:21: abstact ==> abstract
./stacks/JAVA/The_Stock_Span_Problem.java:55: sightly ==> slightly
Error: Process completed with exit code 65.
```

**Comment by TawfikYasser** [comment]
So what is the problem

**Comment by cclauss** [comment]
https://github.com/codespell-project/codespell is finding misspellings that need to be fixed. (Just like in a word processor.)

**Comment by TawfikYasser** [comment]
> https://github.com/codespell-project/codespell is finding misspellings that need to be fixed. (Just like in a word processor.)

Oh okay, Sorry for the misunderstanding
