### ISSUE TITLE
Moving Programming language file to Algorithms folder

### ISSUE THREAD

**Issue by ming-tsai** [MakeContributions/DSA#219]
- [x] C#
- [x] JavaScript
- [x] Python
- [x] Go
- [x] Java
- [x] C
- [x] C++
- [x] Rust
- [x] Haskell

**Comment by TawfikYasser** [comment]
Thanks @ming-tsai I'll start the work soon! Forgive me

**Comment by ming-tsai** [comment]
> Thanks @ming-tsai I'll start the work soon! Forgive me 

Don't worry

**Comment by cyberwizard1001** [comment]
@ming-tsai Can I do C ?

**Comment by ming-tsai** [comment]
> @ming-tsai Can I do C ?

Yes @cyberwizard1001

**Comment by UG-SEP** [comment]
> > @ming-tsai Can I do C ?
> 
> Yes @cyberwizard1001

@atin i am doing this one ??

**Comment by UG-SEP** [comment]
@ming-tsai  first please decide that who will do it else there could be a conflict between me and @atin

**Comment by ming-tsai** [comment]
> @ming-tsai  first please decide that who will do it else there could be a conflict between me and @atin 

Sorry, I didn't remember that you were working on C
SO, @cyberwizard1001 and @atin, do not do it, let @UG-SEP do it

**Comment by UG-SEP** [comment]
i will send you PR in 2 hours 
Thanks

**Comment by UG-SEP** [comment]
but before that you need to check and accept my PR #227 so that i can create a new PR

**Comment by ming-tsai** [comment]
You could create a copy branch of your main

**Comment by UG-SEP** [comment]
ok @ming-tsai

**Comment by ming-tsai** [comment]
Hi guys,
Thanks for your contributions @atin, @Arsenic-ATG, @TawfikYasser, @cclauss, and @UG-SEP
