### ISSUE TITLE
Go tests are failing

### ISSUE THREAD

**Issue by cclauss** [MakeContributions/DSA#230]
https://github.com/MakeContributions/DSA/actions/workflows/go.yml

**Comment by ming-tsai** [comment]
> https://github.com/MakeContributions/DSA/actions/workflows/go.yml

Ok, would you like to help me on this ?

**Comment by ming-tsai** [comment]
Hi @cclauss or @atin,
Could you help me with this issue?

**Comment by atin** [comment]
Not sure what is the issue with golang-ci? maybe this https://github.com/golangci/golangci-lint/issues/825
But using this https://github.com/reviewdog/action-golangci-lint works
