### ISSUE TITLE
Wanted to add height calculation of the tree in c 

### ISSUE THREAD

**Issue by sambit221** [MakeContributions/DSA#237]
Hey @ming-tsai  ,
I Wanted to add height calculation of the tree in c  language.
Please assign me to do that
Thanks

**Comment by ming-tsai** [comment]
Hi @sambit221,
Why are you close this issue?

**Comment by sambit221** [comment]
i was unable to find any folder related to tree in c section

**Comment by ming-tsai** [comment]
@sambit221 here is [the folder path](https://github.com/MakeContributions/DSA/tree/main/algorithms/C)

**Comment by UG-SEP** [comment]
@ming-tsai the issue has been solved
