### ISSUE TITLE
Issue and PR Template

### ISSUE THREAD

**Issue by atin** [MakeContributions/DSA#249]
I think we should add some templates for Issues and Pull Requests. This will help in having some clarity and a consistent format of issues and PRs. For eg. in issues we can create a template for bug report in any of the algorithm and for PRs we can have algorithm details like name etc and a link to it's implementation (if possible) so that reviewer(s) can verify the quickly.

Here are some of the possible templates we can add though adding all of these is not necessary I think.

**Issue**
- [x] #371
- [x] #370
- [x] #369

**Pull Request**
- [x] PR template

**Comment by ming-tsai** [comment]
Does is it done?

**Comment by Sranu2109** [comment]
Is there any issue that I can work upon?

**Comment by ming-tsai** [comment]
> Is there any issue that I can work upon?

Hi @Sranu2109,
For now we don't have, but you could open an issue for new feature or algorithm

**Comment by UG-SEP** [comment]
hey @ming-tsai  can I add a proposal, question and idea template
