### ISSUE TITLE
Wanted to add jump search in c and cpp

### ISSUE THREAD

**Issue by UG-SEP** [MakeContributions/DSA#258]
### Hey @ming-tsai ,
I wanted to add **_jump search_** in c and cpp both languages 
Please assign me to do that 
Thanks

**Comment by Arsenic-ATG** [comment]
implementation of jump search in C++ already exist [here](https://github.com/MakeContributions/DSA/blob/main/algorithms/CPlusPlus/Searching/jump-search.cpp) in this repository

**Comment by UG-SEP** [comment]
yes @Arsenic-ATG i saw but i will implement it using recursion

**Comment by Arsenic-ATG** [comment]
> yes @Arsenic-ATG i saw but i will implement it using recursion

how about you upgrade the already existing one by adding another function to perform it recursively. Like this not only we will not have multiple programs implementing same algo but will also reduce the work you have to do.

**Comment by UG-SEP** [comment]
> w about you upgrade the already existing one by adding another function to perform it recursively. Like this not only we will not have multiple programs implementing same algo but will also reduce the work you have to do.

ok i will do it till night thanks for suggestion
Great idea @Arsenic-ATG
