### ISSUE TITLE
Go and Node.js workflow failing

### ISSUE THREAD

**Issue by UG-SEP** [MakeContributions/DSA#271]
Hey @ming-tsai the go and Node.js workflow are failing 
Please let it to pass 
this should be solve as quick as possible 
Thanks 
![p](https://user-images.githubusercontent.com/75884061/116265573-db3ce200-a798-11eb-84f6-4067290590f7.jpg)

**Comment by ming-tsai** [comment]
Yes, node is filling because the linter but go I don't know

**Comment by UG-SEP** [comment]
> de is filling because the linter but

**Comment by atin** [comment]
![image](https://user-images.githubusercontent.com/61903527/116291186-ef410d80-a7b1-11eb-9823-986dfb017965.png)

The go workflow ran 9 days ago and there was some problem with it but now the problem is fixed. Since then there are no new pull requests on go so the new workflow has not ran yet.

**Comment by ming-tsai** [comment]
It is fixed
![image](https://user-images.githubusercontent.com/37890026/117517672-ba2f7a80-af6a-11eb-8bd3-7f5cabee9840.png)
