### ISSUE TITLE
Head sort on C, C++ and Python

### ISSUE THREAD

**Issue by Sranu2109** [MakeContributions/DSA#286]
Hey @ming-tsai,
I wanted to add heap sort in C, C++ and, python, further want to add docs/en of heap sort please assign me to do that.
Thanks

**Comment by ming-tsai** [comment]
Hi @Sranu2109,
When you finished one of them, please make it checked.
- [x] C
- [ ] C++
- [ ] Python

**Comment by Sranu2109** [comment]
> > Hi @Sranu2109,
> > When you finished one of them, please make it checked.
> > 
> > * [x]   C
> > * [x]   C++
> > * [x]   Python

Done with all of em'

**Comment by ming-tsai** [comment]
Nice work @Sranu2109
