### ISSUE TITLE
Documentation for the algorithms

### ISSUE THREAD

**Issue by ming-tsai** [MakeContributions/DSA#289]
It'd be awesome to have a lot of documentation for the algorithm that was implemented in different languages

🐞 Problem
Currently, we have only a bunch of documentation of the algorithms
🎯 Goal
Have a lot of documentation of the algorithm

💡 Possible solutions
Add documentation of the algorithm

**How to make it?**
Check out [Contribution Guidelines](https://github.com/MakeContributions/DSA/blob/main/docs/en/CONTRIBUTING.md)

📋 Steps to solve the problem

1. Comment below about what you've started working on.
2. Add, commit, push your changes
3. Submit a pull request and add this in comments - Addresses #
4. Ask for a review in the comments section of the pull request
5. Celebrate your contribution to this project 🎉

> Please keep calm  this is an open source project so wait until the reviewer has time to check it out the pull request.

**Comment by UG-SEP** [comment]
@ming-tsai please assign me I wanted to and binary search doc file

**Comment by Vedant488** [comment]
Is this a mistake by any chance? I think this issue should stay open because the documentation will require regular updates as new algorithms are added in the repository.

**Comment by ming-tsai** [comment]
> Is this a mistake by any chance? I think this issue should stay open because the documentation will require regular updates as new algorithms are added in the repository.

Yes

**Comment by SubhamKumarPandey** [comment]
Greetings! I want to contribute for bubble sort, insertion sort, Quick sort, and merge sort. Please assign me so that I will continue working on it.

**Comment by SubhamKumarPandey** [comment]
Greetings @ming-tsai !! I want to contribute for DSA. Please assign me any task so that I will continue working on it.

**Comment by viraj28** [comment]
Hi @ming-tsai, I am new to contributing stuff on open source. Is it okay to write documentation for the code that is already in the algorithms folder or should i write a new algorithm and then a document for it?

if okay, then can i write some documentation?

**Comment by ming-tsai** [comment]
> Hi @ming-tsai, I am new to contributing stuff on open source. Is it okay to write documentation for the code that is already in the algorithms folder or should i write a new algorithm and then a document for it?
> 
> if okay, then can i write some documentation?

Yes @viraj28, I'm waiting your pull request

**Comment by ming-tsai** [comment]
> Greetings @ming-tsai !! I want to contribute for DSA. Please assign me any task so that I will continue working on it.

Yes, you could check this repo if it is missing an algorithm then open an issue about it

**Comment by Gigolino2001** [comment]
Hi @ming-tsai can I start working on Heap sort documentation? Thanks :)

**Comment by ming-tsai** [comment]
> Hi @ming-tsai can I start working on Heap sort documentation? Thanks :)

Yes, I will waiting your pull request

**Comment by ryzheboka** [comment]
Hi @ming-tsai, can I add documentation for ternary search?

**Comment by ryzheboka** [comment]
The implementation of ternary search in C seems to search for a value (that is passed as parameter) in an array. But the Wikipedia page about ternary search defines it as an algorithm that searches for a minimum or maximum of a function. I would like to write documentation for ternary search, but I am a little bit lost there.

**Comment by ming-tsai** [comment]
> The implementation of ternary search in C seems to search for a value (that is passed as parameter) in an array. But the Wikipedia page about ternary search defines it as an algorithm that searches for a minimum or maximum of a function. I would like to write documentation for ternary search, but I am a little bit lost there.

Hi @UG-SEP,
Could you explain his about the algorithm?

**Comment by banerjeesoumya15** [comment]
Hi @ming-tsai ,
Do you want documentation in markdown or code comments?

**Comment by k2491p** [comment]
Hi @ming-tsai ,
I am new to contributing stuff on open source.
I would like to translate `DSA/tree/main/docs/en/Bubble-Sort.md` into Japanese and add to `DSA/tree/main/docs/ja`.
Is it OK?

**Comment by ming-tsai** [comment]
> Hi @ming-tsai ,
> I am new to contributing stuff on open source.
> I would like to translate `DSA/tree/main/docs/en/Bubble-Sort.md` into Japanese and add to `DSA/tree/main/docs/ja`.
> Is it OK?

Ok, I will wait for your pull request.

**Comment by Konnor-Young** [comment]
Hey @ming-tsai 
I am working on the en documentation for count sort. Is that ok?

**Comment by aakgn** [comment]
Hi, could I add documentation for the singly linked list algorithm?

**Comment by aakgn** [comment]
Pull Request: Singly Linked List Documentation #763

**Comment by codesmith25103** [comment]
Should I write Documentation about Vectors?

**Comment by ming-tsai** [comment]
> Should I write Documentation about Vectors (C++)?

There is not obligation for documentation of the algorithms but inside of the algorithm file you should have the comments that reader to understand the process

**Comment by Ayebilla** [comment]
Hi @ming-tsai, may I write the documentation for the doubly linked list? 
Thanks

**Comment by ming-tsai** [comment]
> Hi @ming-tsai, may I write the documentation for the doubly linked list?
> Thanks

Hi @Ayebilla,
Ok I will be waiting for the pull request.

**Comment by pyagnik1** [comment]
Hello @ming-tsai 👋, may I add documentation for balanced trees? Specifically, AVL trees and Red-Black trees. Thanks

**Comment by ming-tsai** [comment]
> Hello @ming-tsai 👋, may I add documentation for balanced trees? Specifically, AVL trees and Red-Black trees. Thanks

Yes, I will be waiting for your pull request.

**Comment by pyagnik1** [comment]
Hello  👋 @ming-tsai I have added a new algorithm, Red Black Tree to the c file, here is the link to my pull request #845. I will add documentation for this algorithm in my next pull request. Please let me know if I can help in any other way. And thanks for giving me a chance.

**Comment by yashdodani** [comment]
May I add some examples on recursion in java?

**Comment by ahmedsilat44** [comment]
I found some typos in the documentation of MinHeap so I Fixed them
![image](https://user-images.githubusercontent.com/105588821/192201897-efa445ac-0720-48d4-bf47-dd31162273b1.png)
the PR is #851

**Comment by charu210703** [comment]
Can I add some code for stacks in python as well as the documentation?

**Comment by pranavyatnalkar** [comment]
Hello @ming-tsai 👋 may I add algorithms to insert and delete an element of a heap in C++? Thank you

**Comment by ming-tsai** [comment]
Hi @charu210703 and @pranavyatnalkar,
Yes, this is an open source project, everyone could make contributions to it.

**Comment by pranavyatnalkar** [comment]
Hello @ming-tsai 👋 I have added a new algorithm, here is the link to my pull request https://github.com/MakeContributions/DSA/pull/866. I am also planning to add its documentation in my upcoming pull request. Thank you for letting me contribute!

**Comment by charu210703** [comment]
Hi @ming-tsai , I have added an algorithm for stacks, here is my pull request #880. Once it is merged, I will also add the documentation for the same. Thank you.

**Comment by tripathisharad** [comment]
Hello @ming-tsai can you assign me this this project I would like contribute on that.

**Comment by mohitkrsuman** [comment]
Hello @ming-tsai I have added a new popular algorithm sudoku solver in Backtracking.

**Comment by Denisthatorf** [comment]
Hi, I contribute for the first time, can I write Dijkstra algorithm documentation?

**Comment by ming-tsai** [comment]
> Hi, I contribute for the first time, can I write Dijkstra algorithm documentation?

Yes, I will be waiting your pull request 😊

**Comment by aayush6200** [comment]
Hey !! I can contribute to DSA. I will actually present a question and solve it through the use of DSA. Assign me. Thanks

**Comment by RK-Shandilya** [comment]
I contributed for first time, reverse linkedlist in groups of size k #1098  . Can you review it ??

**Comment by RK-Shandilya** [comment]
I have generated a pull request of one new file Reverse the ll in groups of K https://github.com/MakeContributions/DSA/pull/1098 . Can you review and approve it ?

**Comment by RK-Shandilya** [comment]
@ming-tsai I have generated a pull request of one new file Reverse the ll in groups of K https://github.com/MakeContributions/DSA/pull/1106. Can you review and approve it ?

**Comment by iamRabia-N** [comment]
Hi! I want to write documentation on "Circular Linked List". Can you assign me this topic. I would like to contribute in it. Thanks.

**Comment by ShadyResurrected** [comment]
Can I write Bellman Ford algorithm documentation?
