### ISSUE TITLE
[Enhancement] Reformatting directory tree of the repository

### ISSUE THREAD

**Issue by Arsenic-ATG** [MakeContributions/DSA#3]
I think the folders in the repo should be ordered on the basis of algorithms instead of programming language.

example : 
currently we have folder in this kind of structure 
```
DSA
| - > Searching 
         | -> C or Cpp 
                  |-> linear search.cpp
```

whereas, it should have the format 
```
DSA
| - > Searching 
         | -> linear search 
                  |-> linear search.cpp
```
like this, it would be easier for both contributors and maintainers to keep track of what algorithms has been implemented in what all languages.

**Comment by Arsenic-ATG** [comment]
I think it would be easier to tackle this right now as this is a new repository and doesn't have a lot of directories and files to move around

**Comment by paulsonjpaul** [comment]
What about other languages? Will it come below `linear search` (just an example)? For example:
```
DSA
| - > Searching 
         | -> linear search 
                  |-> linear search.cpp
                  |-> linear-search.py
```

**Comment by akrish4** [comment]
Hi @Arsenic-ATG @paulsonjpaul 
It would be better if  we don't prefer to have same topic contributed by different members for example  under searching topic we need only one code implementation for one language instead of many contributing to the same topic.
like linear search can be implemented in different languages ( cpp ,java ,py) but it should be only be once , duplicating the same code by different ones is of no use.
what do you say ? 
the directory structure will be like this then isnt it?
```
DSA
| - > Searching 
         | -> linear search 
                  |-> linear search.cpp
                  |-> linear-search.py
                  |-> linear-search.java
``` 
or 

```
DSA
| - > Searching 
         | -> C or Cpp 
                  |-> linear search.cpp
                  |-> binary search.cpp
        | -> java 
                  |-> linear search.cpp
                  |-> binary search.cpp
        | -> python
                  |-> linear search.cpp
                  |-> binary search.cpp
```

both are nice .

**Comment by paulsonjpaul** [comment]
I like the first one:

```
> DSA
> | - > Searching 
>          | -> linear search 
>                   |-> linear search.cpp
>                   |-> linear-search.py
>                   |-> linear-search.java
>          | -> binary search 
>                   |-> binary search.cpp
>                   |-> binary search.py
>                   |-> binary search.java
```

**Comment by akrish4** [comment]
> I like the first one:
> 
> ```
> > DSA
> > | - > Searching 
> >          | -> linear search 
> >                   |-> linear search.cpp
> >                   |-> linear-search.py
> >                   |-> linear-search.java
> >          | -> binary search 
> >                   |-> binary search.cpp
> >                   |-> binary search.py
> >                   |-> binary search.java
> ```

Lets go with this know 
this all are okay with isnt it ? @ming-tsai @paulsonjpaul @Arsenic-ATG

**Comment by ming-tsai** [comment]
The folder name could be on the lower case

**Comment by paulsonjpaul** [comment]
The file name can be hyphened as well:

`linear-search.cpp`, `binary-search.cpp`

**Comment by ming-tsai** [comment]
Hi guys,
I found a problem on the PR #6, we are going to repeat the file's name with the folder, so I change my option, please let me know your suggestions.
```md
DSA
  | searching
    | readme.md
    | cpp
      | linear-search.cpp
      | binary-search.cpp
    | python
      | linear-search.py
      | binary-search.py
    | java
      | linear-search.java
      | binary-search.java
    | csharp
      | linear-search.cs
      | binary-search.cs
```

> @Arsenic-ATG, @akrish4, and @paulsonjpaul

**Comment by paulsonjpaul** [comment]
Ok. That looks more organized. A small suggestion. The topic can be capitalized so that it is recognizable as a topic. Also, `readme` should be capitalized:

```
DSA
  | SEARCHING
    | README.md -> should create an readme for the index
    | c-or-cpp
      | linear-search.cpp
      | binary-search.cpp
    | python
      | linear-search.py
      | binary-search.py
    | java
      | linear-search.java
      | binary-search.java
    | csharp
      | linear-search.cs
      | binary-search.cs
```

**Comment by paulsonjpaul** [comment]
Before merging #6, we need to merge #7. Else it would cause problems.

**Comment by Arsenic-ATG** [comment]
@ming-tsai if you want to keep the old one then it's totally fine, I don't think it will make any huge impact on the contributors and at the end of the day it's you (along with @akrish4 ) who are going to moderate this repository so it's structure should be the one which suits you both better, than anyone else here.

So do you want me to update the PR and switch the structure back to format you suggested ?

that is :-
```
DSA
  | SEARCHING
    | README.md -> should create an readme for the index
    | c-or-cpp
      | linear-search.cpp
      | binary-search.cpp
    | python
      | linear-search.py
      | binary-search.py
    | java
      | linear-search.java
      | binary-search.java
    | csharp
      | linear-search.cs
      | binary-search.cs
```

**Comment by ming-tsai** [comment]
> @ming-tsai if you want to keep the old one then it's totally fine, I don't think it will make any huge impact on the contributors and at the end of the day it's you (along with @akrish4 ) who are going to moderate this repository so it's structure should be the one which suits you both better, than anyone else here.
> 
> So do you want me to update the PR and switch the structure back to format you suggested ?
> 
> that is :-
> ```
> DSA
>   | SEARCHING
>     | README.md -> should create an readme for the index
>     | c-or-cpp
>       | linear-search.cpp
>       | binary-search.cpp
>     | python
>       | linear-search.py
>       | binary-search.py
>     | java
>       | linear-search.java
>       | binary-search.java
>     | csharp
>       | linear-search.cs
>       | binary-search.cs
> ```
> 

Yes @Arsenic-ATG, but remember every folders and files should be on lower case, only the readme as this `README.md`

**Comment by ming-tsai** [comment]
Hi @Arsenic-ATG,
PR #7 is merged, please update your branch, thanks
