### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by aayushjain7** [MakeContributions/DSA#306]
How can I remove previous commits that are already been merged so that when I create a new pull request the older commits does not get included in a new pull request?

**Comment by aayushjain7** [comment]
#305 
Here you can see my older commits which are already been merged. How can I avoid them getting included in a new pull request?

**Comment by Ashborn-SM** [comment]
hope this helps - https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

**Comment by ming-tsai** [comment]
> #305 
> Here you can see my older commits which are already been merged. How can I avoid them getting included in a new pull request?

You just need to update your fork, and make change

**Comment by Ashborn-SM** [comment]
> > #305
> > Here you can see my older commits which are already been merged. How can I avoid them getting included in a new pull request?
> 
> You just need to update your fork, and make change

How do i update my fork?
re-fork?
git pull?

**Comment by aayushjain7** [comment]
> hope this helps - https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

Thanks.

**Comment by aayushjain7** [comment]
> > #305
> > Here you can see my older commits which are already been merged. How can I avoid them getting included in a new pull request?
> 
> You just need to update your fork, and make change

I do update them. I fetch the changes from the original repository

**Comment by ming-tsai** [comment]
Ok
