### ISSUE TITLE
Template for list of problems

### ISSUE THREAD

**Issue by ani1998ket** [MakeContributions/DSA#309]
I suggest creating empty files in each language directory for every problems that has been implemented or needs to be implemented. 
This way there will be a consistency in the list of problems  and one can just focus on implementing a problem in any particular language.

**Comment by ming-tsai** [comment]
Hi @ani1998ket,
I'm disagree with this case, due to we don't have to create a file that doesn't have implementation, and this repo is let the developer to learn how to contribute a open source project.
Coding, reviewing, discuss, and apply the suggestions is the process of the contribution.
