### ISSUE TITLE
I would like to join this organization to add DS and Algorithms

### ISSUE THREAD

**Issue by JayantGoel001** [MakeContributions/DSA#338]

**Comment by Arsenic-ATG** [comment]
Actually it's the other way around. 

in order to join this organisation, one must add DS and Algorithms to the repository.

**Comment by ming-tsai** [comment]
Hi @JayantGoel001,
You were invited as a member of this organization.
> The invitation [link](https://github.com/MakeContributions)

**Comment by JayantGoel001** [comment]
> Hi @JayantGoel001,
> You were invited as a member of this organization.
> 
> > The invitation [link](https://github.com/MakeContributions)

Thanks 🙂
