### ISSUE TITLE
Add breadth first search algorithm in DSA/algorithms/CPlusPlus/Graphs/

### ISSUE THREAD

**Issue by hkumar0132** [MakeContributions/DSA#361]
I would like to add breadth first search algo in DSA/algorithms/CPlusPlus/Graphs/

**Comment by hkumar0132** [comment]
I dont know how this works but I have created PR #362

**Comment by UG-SEP** [comment]
Hey @hkumar0132  are you new to Open-Source

**Comment by UG-SEP** [comment]
I have assigned you to the issue but please remember It from next time 
Waiting for the PR update

**Comment by hkumar0132** [comment]
Working on it, thanks

**Comment by hkumar0132** [comment]
I have made the necessary changes
