### ISSUE TITLE
Check Cycle in Directed Graph using C++

### ISSUE THREAD

**Issue by kartikeya100** [MakeContributions/DSA#377]
## Information about Algorithm
Given list of edges in a directed Graph, the algorithm will check if there is a cycle present in it.

> Input: [[0,1],[1,3],[0,2],[2,3],[3,0]]
> Output: True
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [X] Yes
- [ ] No

**Comment by ming-tsai** [comment]
> ## Information about Algorithm
> Given list of edges in a directed Graph, the algorithm will check if there is a cycle present in it.
> 
> > Input: [[0,1],[1,3],[0,2],[2,3],[3,0]]
> > Output: True
> ### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)
> 
> - [X] Yes
> - [ ] No

Who you like to implement it?

**Comment by kartikeya100** [comment]
Pull #378 added.
