### ISSUE TITLE
updating README.md add steps to PR 

### ISSUE THREAD

**Issue by Amisha-Mohapatra** [MakeContributions/DSA#38]
Need to add some detailed information and steps how to create an issue and pull request.
 
It will be helpful for beginners to start with.

**Comment by paulsonjpaul** [comment]
Do have any specific format in mind? Please tell us which part was not clear.

**Comment by Amisha-Mohapatra** [comment]
@paulsonjpaul For beginners to start with open source contribution we can add some steps as documentation by which they will be comfortable with creating a pull request and an issue.

**Comment by paulsonjpaul** [comment]
Would it be nice if we move the guidelines to a `CONTRIBUTING.md` file? I think it will be more specific and semantic than adding it in the `README.md`.

> @ming-tsai, please give your thoughts

**Comment by Amisha-Mohapatra** [comment]
@paulsonjpaul  yah that will be a better option.

**Comment by paulsonjpaul** [comment]
@Arsenic-ATG

**Comment by Arsenic-ATG** [comment]
That is a good idea, as there is no such file which instructs especially beginners how to contribute to this repository. I am totally ok with it. 

I think you should get in touch with @ming-tsai , because if I remember correctly, he was already working on contributions.md for this repository.

**Comment by ming-tsai** [comment]
Hi @Amisha-Mohapatra,
We could create like this [example](https://github.com/firstcontributions/first-contributions#first-contributions)

**Comment by Amisha-Mohapatra** [comment]
@ming-tsai this example is really good. It clearly described the steps. Sure I would like to help you with this.

**Comment by ming-tsai** [comment]
> @ming-tsai this example is really good. It clearly described the steps. Sure I would like to help you with this.
Nice @Amisha-Mohapatra , let me know any update
