### ISSUE TITLE
[To contributors] Add missing data structure code from a supporting repo

### ISSUE THREAD

**Issue by jishanshaikh4** [MakeContributions/DSA#395]
I see this is a good repository for data structures and algorithms. If contributors like to add some code, here https://github.com/jishanshaikh4/CSE-217-Data-Structures-Laboratory

Feel free to copy/add code chunk/full from there, just @ me.

Thanks.

**Comment by jishanshaikh4** [comment]
The language there is **C++/C**

**Comment by ming-tsai** [comment]
Hi @jishanshaikh4,
I will waiting your pull request

**Comment by jishanshaikh4** [comment]
@ming-tsai Say less. Give me 48 hours. Ping me if I slept over :smile:

**Comment by ming-tsai** [comment]
> @ming-tsai Say less. Give me 48 hours. Ping me if I slept over :smile: 

Ok, don't worries

**Comment by jishanshaikh4** [comment]
See PR #402

**Comment by juhi1999** [comment]
Hi, I am new to contribution. I forked dsa contribution on my system then .c files were not getting opened so I renamed it to .txt then I added a new DS algorithm but that again is in txt format. I tries rechanging its name to .c but again format it .txt.. I want to commit but I havn't.. what should I do next??? Please guide me.

**Comment by ming-tsai** [comment]
> Hi, I am new to contribution. I forked dsa contribution on my system then .c files were not getting opened so I renamed it to .txt then I added a new DS algorithm but that again is in txt format . Do i need to change it? I tries rechanging its name to .c but again format it .txt.. I want to commit but I havn't.. what should I do next??? Please guide me. and how to generate pull request after that?

Hi @juhi1999, 
Please check this [discussion](https://github.com/MakeContributions/DSA/discussions/383) any question please comment on it
