### ISSUE TITLE
Generic programming in C

### ISSUE THREAD

**Issue by Ashborn-SM** [MakeContributions/DSA#398]
## Information about Algorithm

@ming-tsai is Generic Programming relevant here in this repo?

### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

None

**Comment by ming-tsai** [comment]
Nop

**Comment by Ashborn-SM** [comment]
alright,
Thanks for the quick response @ming-tsai

**Comment by ming-tsai** [comment]
> alright,
> Thanks for the quick response @ming-tsai 
> 

You welcome, are you going to programming on it? You could as this on discord
