### ISSUE TITLE
Find the element that appears thrice

### ISSUE THREAD

**Issue by prakashsingh1609** [MakeContributions/DSA#426]
## Information about Algorithm

Finds the element that appears thrice in an array in O(n) time. It is one of the most important interview question.

### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

Hey @aayushjain7 , I want to add this imp interview question in the "DSA/algorithms/CPlusPlus/Arrays/" .

**Comment by aayushjain7** [comment]
@prakashsingh1609 Go ahead! 👍🏼

**Comment by krishna0303** [comment]
Hey can i work on this issue?

**Comment by ming-tsai** [comment]
Hi @krishna0303,
This algorithm is working @prakashsingh1609, but if you want to contribute this repo, please add another algorithm that is not exists
