### ISSUE TITLE
Huffman Encoding in Cpp

### ISSUE THREAD

**Issue by KareimGazer** [MakeContributions/DSA#466]
## Information about Algorithm
This algorithm encodes information reducing the size.
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context
I used this algorithm in one of my college projects to reduce file size and it reduced it to half.

**Comment by ming-tsai** [comment]
> ## Information about Algorithm
> This algorithm encodes information reducing the size.
> 
> ### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)
> * [x]  Yes
> * [ ]  No
> 
> ## Other context
> I used this algorithm in one of my college projects to reduce file size and it reduced it to half.

Hi @KareimGazer,
Waiting for your pull request
