### ISSUE TITLE
Palindrome Number in C++

### ISSUE THREAD

**Issue by kumarsyadav2** [MakeContributions/DSA#481]
## Information about Algorithm
This algorithem is used to check whether reverse of a number is equals to original number or not.

(Type here)
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

(Type here)

**Comment by ming-tsai** [comment]
Hi @kumarsyadav2,
I will wait for your pull request

**Comment by kumarsyadav2** [comment]
i have already made a pull request few days ago for adding armstrong number, also made successful submission yesterday.
Do i need to make a new pull request for making this new submission? or i can continue with old pull request? @ming-tsai @member

**Comment by Ashborn-SM** [comment]
> i have already made a pull request few days ago for adding armstrong number, also made successful submission yesterday.
> Do i need to make a new pull request for making this new submission? or i can continue with old pull request? @ming-tsai @member

@kumarsyadav2  you need to make a new PR for each unique task. Your old PR has been merged so there's not much you can do about it,  we could revert it back but it will be a mess, so better to make a new PR for this new change.
Also when you mention `@member` you are pinging a user with that username(just click on that `@member` and see if for yourself), so don't do that.

**Comment by kumarsyadav2** [comment]
@Ashborn-SM my intention is to mentioning member of this organisation whenever I have written ```@member```,
Although thanks for concerning

**Comment by Ashborn-SM** [comment]
> @Ashborn-SM my intention is to mentioning member of this organisation whenever I have written `@member`,
> Although thanks for concerning
> 
> Also why I am not able to add label, neither to conversation nor issues, pull request?!

mention atmost one or two that will be enough and make sure you get their username right.
Only those with permissions can add label and such things, first time contributors or members can't do that.

**Comment by kumarsyadav2** [comment]
@ming-tsai can you please allow me add labels? to avoid mess-up and mistakes I will only add lables to my own issues, conversation/pull request!

**Comment by ming-tsai** [comment]
> @ming-tsai can you please allow me add labels? to avoid mess-up and mistakes I will only add lables to my own issues, conversation/pull request!

Wich is the labels that do you want to add?

**Comment by kumarsyadav2** [comment]
> > @ming-tsai can you please allow me add labels? to avoid mess-up and mistakes I will only add lables to my own issues, conversation/pull request!
> 
> Which is the labels that do you want to add?

i will be add labels like C++ when i will create new issue or pull-request in CPlusPlus

**Comment by ming-tsai** [comment]
> > > @ming-tsai can you please allow me add labels? to avoid mess-up and mistakes I will only add lables to my own issues, conversation/pull request!
> > 
> > Which is the labels that do you want to add?
> 
> i will be add labels like C++ when i will create new issue or pull-request in CPlusPlus

Ok, don't worries I will assign it by myself
