### ISSUE TITLE
Prime Number in C++

### ISSUE THREAD

**Issue by kumarsyadav2** [MakeContributions/DSA#496]
## Information about Algorithm

Write a program in cpp to calculate the given number is prime or not
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

It is a general maths problem

**Comment by ming-tsai** [comment]
> @ming-tsai is Make Contribution's Repository comes under hacktoberfest?

Nope, I don't have idea about it, could you explain me?

**Comment by kumarsyadav2** [comment]
Hacktoberfest is a festival for open-source contributors which begins on 1st October every year from last 8 year.
There are some conditions for a repository to eligible for participating in hacktoberfest.
Kindly do some research on how to make make eligible our repository for hacktoberfest.
For more information do visit: hacktoberfest.digitalocean.com

**Comment by kumarsyadav2** [comment]
Hey @ming-tsai can you please label this issue with ```hacktoberfest``` label?
Actually hacktoberfest program is beginning tonight 12:00AM

**Comment by kumarsyadav2** [comment]
@ming-tsai kindly linked this issue to pull request i have made

**Comment by kumarsyadav2** [comment]
Hey @Divya333  It's great that you are willing to work on this but i am currently working on it in a hectic schedule.
kindly find a new issue or create one to work with
