### ISSUE TITLE
odd-even in C++

### ISSUE THREAD

**Issue by kumarsyadav2** [MakeContributions/DSA#501]
## Information about Algorithm

A program to check odd and even numbers in cpp
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

it is a general maths problem

**Comment by kumarsyadav2** [comment]
@ming-tsai , extremely sorry for the delay, i am working on it.

**Comment by shivanithorve01** [comment]
hello I am Shivani. can you assign this issue to me ?

**Comment by prehans** [comment]
Hello @kumarsyadav2 can you assign this to me?

**Comment by Jaraxxxx** [comment]
@ming-tsai I am willing to contribute to this issue can you assign me this issue?

**Comment by ming-tsai** [comment]
> @ming-tsai I am willing to contribute to this issue can you assign me this issue?

Please ask for @kumarsyadav2.

**Comment by kumarsyadav2** [comment]
> @ming-tsai I am willing to contribute to this issue can you assign me this issue?

@Jaraxxxx sure! you can work on this.
go ahead, wishing you best!
@ming-tsai

**Comment by NSHU17** [comment]
Looks open still, can I complete? @kumarsyadav2 @Jaraxxxx @ming-tsai

**Comment by kumarsyadav2** [comment]
@NSHU17 sure!! go ahead and complete it.

**Comment by en1gm479** [comment]
Looks like this issue is still open, can you assign this to me? @ming-tsai @NSHU17 @kumarsyadav2

**Comment by kumarsyadav2** [comment]
@en1gm479 go ahead

**Comment by en1gm479** [comment]
@ming-tsai @kumarsyadav2 I've made the PR, anyone pls review it.
