### ISSUE TITLE
Infix to postfix conversion in CPlusPlus

### ISSUE THREAD

**Issue by Manas-Tiwari** [MakeContributions/DSA#515]
## Information about Algorithm
Infix to postfix conversion algorithm takes an array of string (infix form) and converts it to postfix form using STACK.
(Type here)
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

(Type here)
This is a famous coding problem present on codewars, codechecf, hackerrank etc.

**Comment by Manas-Tiwari** [comment]
with ref. to this issue/suggestion, i have submitted a PR #514.
please review it.
Thank you

**Comment by isharawat** [comment]
claim

**Comment by Manas-Tiwari** [comment]
claim ? @isharawat can you please explain a little bit .
