### ISSUE TITLE
Odd-Even in C

### ISSUE THREAD

**Issue by kumarsyadav2** [MakeContributions/DSA#553]
## Information about Algorithm

A program in C used to calculate whether the given number odd number or even number
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

**Comment by ming-tsai** [comment]
Hi @kumarsyadav2,
Are you working on this one?

**Comment by LuigiAltamura** [comment]
Hi @ming-tsai, if @kumarsyadav2 is not working anymore on this issue I can work on it! Otherwise I will choose another one

**Comment by ming-tsai** [comment]
Hi @kumarsyadav2,
Could you respond to him?

**Comment by kumarsyadav2** [comment]
Hi @LuigiAltamura you can work on this!
currently I am not working on this.
@ming-tsai
