### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by ming-tsai** [MakeContributions/DSA#561]
<div align="center">
    <img alt="" align="center" width="400px" src="https://user-images.githubusercontent.com/50463866/135718788-5e4b1937-6593-47db-b6d8-789d89f39097.png"/>

**Open source is changing the world – one contribution at a time.**

**Support open source throughout October!**

Hacktoberfest encourages participation in the open-source community, which grows bigger every year. Complete the 2021 challenge and earn a limited-edition T-shirt.
</div>

## Hacktoberfest and Make Contributions
Public APIs is participating in hacktoberfest 2021 and needs your help to improve it even more. Please feel free to open questions/request requests and we will be happy to review your contribution. :octocat:

## Important
Before making any contribution, please read our [contribution guide](https://github.com/MakeContributions/DSA#contribution-guidelines) to help you out.

After you make your contribution, a sequence of automated tests will be run to expedite a review by one of the @MakeContributions/dsa-reviewers.

Please stay tuned for test results. They will inform you as quickly as possible if your contribution has any problems. If the tests fail, your contribution has a problem and must be fixed in order to be merged.

**Example of test failure:**

![image](https://user-images.githubusercontent.com/37890026/136815019-f88065a3-6225-4a6a-97b5-aec7862a9984.png)

See more information about the failure by clicking on the `Details` link

**Example of test success:**

![image](https://user-images.githubusercontent.com/37890026/136814941-103b9fea-1cf8-4353-a62e-7b938c118253.png)

Learn more about Hacktoberfest 2021 at: https://hacktoberfest.digitalocean.com/

**Comment by prehans** [comment]
@ming-tsai can you please assign this issue to me?
