### ISSUE TITLE
Give problem in python

### ISSUE THREAD

**Issue by Prashant0kgp** [MakeContributions/DSA#580]
## Information about Algorithm

(Type here)
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

(Type here)

**Comment by ming-tsai** [comment]
Hi @Prashant0kgp,
What do you close this issue?

**Comment by Prashant0kgp** [comment]
No, I was thinking this repo belongs only to C++ and java students that why I close it.
thank you!
