### ISSUE TITLE
Merge Intervals in c++

### ISSUE THREAD

**Issue by anujjain5699** [MakeContributions/DSA#607]
## Merge Intervals
merge all overlapping intervals
## Other context
[Leetcode](https://leetcode.com/problems/merge-intervals/)

**Comment by anujjain5699** [comment]
@ming-tsai 
Plz help me ,how can I solve this

> This branch is 2 commits ahead of MakeContributions:main.

for my fork repo

**Comment by anujjain5699** [comment]
i already do 
**fetch and merge**

**Comment by ming-tsai** [comment]
> i already do **fetch and merge**

You have to open a pull request to our branch
