### ISSUE TITLE
BUG in bubble-sort.js

### ISSUE THREAD

**Issue by underager** [MakeContributions/DSA#646]
**Bug detail**

file name : [bubble-sort.js](algorithms/JavaScript/src/sorting/bubble-sort.js)

**Counter example**

bubbleSort([23, 34, 25, 12, 54, 11]));
should return // [11, 12, 23, 25, 34, 54]
instead it returns [23, 25, 12, 34, 11, 54]
it just pushes the biggest number to the end and does not sort the array.

I would like to submit the pull request for the same.

**Additional context**

**Comment by lokesh-0706** [comment]
Can you assign me this issue

**Comment by ming-tsai** [comment]
> Can you assign me this issue

This is the pull request #647 for this issue
