### ISSUE TITLE
Add Quick Sort Algorithm in C

### ISSUE THREAD

**Issue by AnishLohiya** [MakeContributions/DSA#651]
## Information about Algorithm

Quick Sort Algorithm in C
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [X] Yes
- [ ] No

## Other context

(Type here)

**Comment by sujana-kamasany** [comment]
Hello, I would like to contribute for this issue!

**Comment by ming-tsai** [comment]
@AnishLohiya are you going to work this issue?

**Comment by AnishLohiya** [comment]
> @AnishLohiya are you going to work this issue?

Yes
