### ISSUE TITLE
Add Stacks in C Language

### ISSUE THREAD

**Issue by sonustark1** [MakeContributions/DSA#654]
## Information about Algorithm

Add Stack using arrays and stack using linkedlist
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [X] Yes
- [ ] No

## Other context

None

**Comment by AnishLohiya** [comment]
Hey, @ming-tsai Can I Work on this issue ?

**Comment by ming-tsai** [comment]
> Hey, @ming-tsai Can I Work on this issue ?

If @sonustark1 doesn't want to work on this issue

**Comment by sonustark1** [comment]
> > Hey, @ming-tsai Can I Work on this issue ?
> 
> If @sonustark1 doesn't want to work on this issue

@ming-tsai  you can Assign him the issue if he wants to work on it.

**Comment by ming-tsai** [comment]
> > > Hey, @ming-tsai Can I Work on this issue ?
> > 
> > If @sonustark1 doesn't want to work on this issue
> 
> @ming-tsai  you can Assign him the issue if he wants to work on it.

Ok
