### ISSUE TITLE
Naismith's rule in C#

### ISSUE THREAD

**Issue by simonkarofillidis** [MakeContributions/DSA#658]
## Information about the Algorithm

I would like to do an implementation of Naismith's rule in **C#**, the algorithm will make use of several user inputs for locations and several other integers to do the multiple calculations needed and print the according results for the intended route in detail.
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context
None.

**Comment by simonkarofillidis** [comment]
> Hi @simonkarofillidis, I will wait for your pull request.

Thanks! I will make a branch and deliver one soon!

**Comment by simonkarofillidis** [comment]
@ming-tsai 
Hello! I have made a new push to my branch which fixes, also made a good addition to make it more user friendly by adding some separating lines between the outputs. So they are clearer now, and i am sure it will pass the code-spell now! If anything goes wrong please tell me.

**Comment by ming-tsai** [comment]
> @ming-tsai 
> Hello! I have made a new push to my branch which fixes, also made a good addition to make it more user friendly by adding some separating lines between the outputs. So they are clearer now, and i am sure it will pass the code-spell now! If anything goes wrong please tell me.

Ok, I will check it out
