### ISSUE TITLE
prefix to postfix in cpp

### ISSUE THREAD

**Issue by stutimohta20** [MakeContributions/DSA#661]
## Information about Algorithm
It will convert the expression from prefix form to postfix form
(Type here)
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

**Comment by ming-tsai** [comment]
Hi @stutimohta20,
I will wait for your pull request.
