### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TawfikYasser** [MakeContributions/DSA#68]
Hi

I suggest to add a GitHub action to the repository, to display a welcome message for contributor who opens an `Issue` or `PR`

If the idea is good, I can do it, I have this action, and I can add it to work,

If you you agree, and assigned it to me, Please tell me the message you want to display it.

Thanks

**Comment by ming-tsai** [comment]
Hi @TawfikYasser,
Nice idea, what do you think @paulsonjpaul, @Arsenic-ATG, and @akrish4?

**Comment by TawfikYasser** [comment]
Thanks @ming-tsai  :)

**Comment by TawfikYasser** [comment]
### It will be like this 👇 @ming-tsai 

![image](https://user-images.githubusercontent.com/54971231/107531061-247f8b80-6bc5-11eb-8e73-05fed667efc0.png)

**Comment by ming-tsai** [comment]
Nice

**Comment by Arsenic-ATG** [comment]
can't we have one which automatically adds relevant language tab on the PR ? 😅

btw this looks nice 👍

**Comment by TawfikYasser** [comment]
@Arsenic-ATG I think there is one like this > adds relevant language label on the PR

I am waiting for confirmation about `Welcome Action`

**Comment by TawfikYasser** [comment]
Thanks

**Comment by ming-tsai** [comment]
It's sounds good, we could add it by checking file changed

**Comment by TawfikYasser** [comment]
@ming-tsai 

Okay I will add the action

**Comment by ming-tsai** [comment]
> @ming-tsai 
> 
> Okay I will add the action 

Could be on the same action

**Comment by TawfikYasser** [comment]
Sorry, What you mean @ming-tsai ?

**Comment by TawfikYasser** [comment]
PR opened here #73

**Comment by ming-tsai** [comment]
> Sorry, What do you mean @ming-tsai ?

I mean on the same action you could make write the message and assign the labels

**Comment by TawfikYasser** [comment]
Okay @ming-tsai  I will try to make it soon.
