### ISSUE TITLE
graph cycle detection using union-find algorithm in C++

### ISSUE THREAD

**Issue by helarious99** [MakeContributions/DSA#680]
## Information about Algorithm

The algorithm will detect if a graph contains a cycle by using disjoint sets.
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

(Type here)

**Comment by ming-tsai** [comment]
Hi @helarious99,
I will wait for you pull request.
