### ISSUE TITLE
uniform cost search algorithm in python

### ISSUE THREAD

**Issue by GAbdulWahab** [MakeContributions/DSA#722]
## uses the lowest cumulative cost to find a path from the source to the destination.

i.e: What the given algorithm do and i.e. Type of algorithm array,stack
1-Insert the root node into the priority queue
2-Repeat while the queue is not empty:
3-Remove the element with the highest priority
If the removed node is the destination, print total cost and stop the algorithm
Else, enqueue all the children of the current node to the priority queue, with their cumulative cost from the root as priority
Type it is searching using graph

### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

(Type here)

**Comment by GAbdulWahab** [comment]
@ming-tsai 
Yes, why my pr not accept?

**Comment by ming-tsai** [comment]
> @ming-tsai Yes, why my pr not accept?

Nop @sridhar-5 will be validate the pull request.

**Comment by GAbdulWahab** [comment]
@ming-tsai  why my algorithm not merge, @sridhar-5  is reviewed it and he says it good and I fixed the problem in grammar

**Comment by ming-tsai** [comment]
Hi @GAbdulWahab,
History said after approving it, @sridhar-5 found some spelling errors, so he make a request change for you.
After you push the change he has to review it again.

**Comment by GAbdulWahab** [comment]
@ming-tsai  ok, sorry  , thanks
