### ISSUE TITLE
Depth-first search in python 

### ISSUE THREAD

**Issue by ghost** [MakeContributions/DSA#734]
## Information about Algorithm

(Type here)
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

(Type here)

**Comment by ming-tsai** [comment]
Hi @PrathameshSahasrabuddhe,
I have assign to you the issue
