### ISSUE TITLE
Broken Link in Java/README.md file

### ISSUE THREAD

**Issue by mohitchakraverty** [MakeContributions/DSA#840]
**Bug detail**

Name of the file in which the bug is present. Additionally, you can also add the line number and/or a code snippet of the bug.
DSA/algorithms/Java/README.md
Under Tree :
At Line  103: Random node of a binary tree
**Counter example**
The link does not work and is not linked to its respective file.

**Comment by christophermorin** [comment]
Hello, I'd like to fix this.
