### ISSUE TITLE
Roman Numerals Converter in Java

### ISSUE THREAD

**Issue by kparaske** [MakeContributions/DSA#846]
## Information about Algorithm

I would like to implement an algorithm that converts decimal integers to roman numerals and vice versa.
### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

None.

**Comment by Harshit-3905** [comment]
I would like to work on this issue . Can You assign me ?

**Comment by chhotu2** [comment]
Hello!  can you assign this issue to me ?
