### ISSUE TITLE
Regression after merging #849

### ISSUE THREAD

**Issue by Arsenic-ATG** [MakeContributions/DSA#887]
Pull request #849 was merged even though the changes weren't passing all the checks, causing a regression check failure in all the PRs opened after it.

**Comment by Arsenic-ATG** [comment]
@MakeContributions/dsa-reviewers, please make sure the PR passes all the checks before approving it.

**Comment by ming-tsai** [comment]
Hi @Arsenic-ATG and @mohitchakraverty,
Does this issue is solved?

**Comment by mohitchakraverty** [comment]
No, I think We will have to revert both the merge 
#901
#849

**Comment by mohitchakraverty** [comment]
Yes, it is fixed but everyone needs to update their branch to merge the latest changes from the upstream repository into their branch in their forked repo.
