### ISSUE TITLE
[Enhancement] Solution folder and Github Action

### ISSUE THREAD

**Issue by ming-tsai** [MakeContributions/DSA#9]
Actually, we have a problem, that we don't know if the file it's building correctly or not, so my recommendation is below.
1. Reformation of directories
```md
DSA
  | c-or-cpp
    | readme.md -> should create an readme for the index
    | solution file or project
    | search
      | linear-search.cpp
      | binary-search.cpp
    | sorting
      | some-sort.cpp
  | java
    | readme.md -> should create an readme for the index
    | solution file or project
    | search
      | linear-search.java
      | binary-search.java
    | sorting
      | some-sort.java
```
2. Create Github action for building the solutions

Waiting for your suggestions @Arsenic-ATG, @paulsonjpaul, and @akrish4

**Comment by Arsenic-ATG** [comment]
And what will `solution file or project` contain ? 🤔

**Comment by ming-tsai** [comment]
> And what will `solution file or project` contain? 🤔
For example on csharp it's `.sln` or `.csproj`
