### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by TawfikYasser** [MakeContributions/DSA#90]
The problem is that reviewing PR is to late

**Comment by Arsenic-ATG** [comment]
@TawfikYasser ,reviewing process takes time as right now we don't have a lot reviewers, and we can't just blindly merge all the pull requests that people create as we don't want any faulty code to pollute the repository.

if you want to volunteer then you can also put your reviews on any of the open pull requests if you find anything faulty in them or any edge case which the poster missed, It will make it much convenient for other reviewers to post the review and make the overall reviewing process much faster.

**Comment by TawfikYasser** [comment]
Okay Thanks @Arsenic-ATG
