### ISSUE TITLE
Single occurring element in array in JavaScript.

### ISSUE THREAD

**Issue by Pranav-Rustagi** [MakeContributions/DSA#909]
## Finding element appearing only once in an array having other elements appearing twice.

The input for the problem is an array. The algorithm uses bitwise operations to find the single occurring element in O(1) extra space, and O(n) time complexity.

### Have you read the [Contributing.md](https://github.com/MakeContributions/DSA/blob/main/CONTRIBUTING.md) and [Code of conduct](https://github.com/MakeContributions/DSA/blob/main/CODE_OF_CONDUCT.md)

- [x] Yes
- [ ] No

## Other context

An easy-level problem on GeeksForGeeks for CPP/C/Java.

**Comment by Pranav-Rustagi** [comment]
@ming-tsai Can you please assign it to me?

**Comment by Amit-exe** [comment]
@ming-tsai assign it to me
