### ISSUE TITLE
Add Makefiles to Source-Codes (especially in  C/C++)

### ISSUE THREAD

**Issue by gauthamkrishna9991** [MakeContributions/DSA#97]
In C/C++, it's especially important for one to properly use compilers to get similar outputs, across platforms.

It's especially useful in cases where the user just has to run `make` to compile and execute / interpret the program, rather than search for 'how to compile X' or 'how to run Y'. For a lot of these cases, a `Makefile` defining the build recipe would assist a lot, along with automation directly from it.

**Comment by Arsenic-ATG** [comment]
I don't think there is any requirement of it especially right now. 

right now all the files there in the repository contains very basic programs which can easily be compiled/interpreted by any standard compiler/interpreter out there in just single compiler command or on a click of a button. `Makefile` would have been a great help in case there exist programs that span over multiple files and/or require linking to multiple additional libraries etc. 

and as the repository is totally algorithm and data-structures cantered where each code file focusses on one single algorithm/data-strucure only, I don't think such condition will happen anytime in near future.
